model_path: /home/sriramv1/manas_ada/users/sriramv1/tofu-main/paper_models/final_ft_noLORA_5_epochs_inst_lr0.0002_pythia-1.4_full/checkpoint-2500
save_dir: ${model_path}

data_path: locuslab/TOFU
split: full
eval_task: eval_log
question_key: question
answer_key: answer

generation:
  max_length: 200
  max_new_tokens: null
save_generated_text: true
ds_size: 4000

overwrite: true
use_pretrained: false

model_family: pythia-1.4
